provider:
  name: faas
  gateway: http://localhost:8080

functions:
  release:
    lang: python
    handler: ./release
    image: alexellis/release:latest

  nameexists:
    lang: node
    handler: ./nameexists
    image: alexellis/nameexists

