# gh-latest-release (re-po)
provider:
  name: faas
  gateway: http://localhost:8080


functions:
  release:
    lang: python
    handler: ./release
    image: alexellis/release:latest
  releases:
    lang: python
    handler: ./release
    image: alexellis/releases:latest
    
  nameexists:
    lang: node
    handler: ./nameexists
    image: alexellis/nameexists:0.1

# A commit event will build, ship and run your functions
# Apply labels
